local M = {
  job = nil,
  mode = "normal",
  co = nil,
  send = nil,
}

local Split = require("nui.split")
local Layout = require("nui.layout")

local function highlight_console()
  vim.cmd([[
    syntax clear
    syntax match GdbLink /<.*>/
    syntax match GdbVersion /GNU gdb (GDB) .\+/
    syntax match GdbImportItem /Reading symbols from .\+/
    syntax match GdbImportItem /Core was generated by .\+/
    syntax match GdbAddress / \<0x[0-9a-z]\+\> /
    syntax match Conceal /=\zs\<0x[0-9a-z]\+\> /
    syntax match GdbFunction /in \zs[^ ]\+/
    syntax match GdbArgs /\<\zs\w\+\ze\>=/
    syntax match GdbSource /) from \zs.*$/
    syntax match GdbSource /at \zs[^ ]\+:\d\+$/
    highlight GdbLink guifg=#84a800 
    highlight GdbVersion guifg=#bb9af7 gui=bold
    highlight GdbImportItem guifg=#bc84a8 
    highlight GdbAddress guifg=#268bd2
    highlight GdbFunction guifg=#e0af68
    highlight GdbArgs guifg=#887ec8
    highlight GdbSource guifg=#2aa198
  ]])
end

local function highlight_frame()
  vim.cmd([[
    syntax clear
    syntax match Title /^Frame$/
    syntax match CursorLineNr /  \zs\d\+\ze[\t\s]\+/
    syntax match String /▸ .*/
  ]])
end

local function highlight_locals()
  vim.cmd([[
    syntax clear
    syntax match Title /^Locals$/
    syntax match GdbArgs /\<\zs\w\+\ze\> =/
    syntax match Conceal / = \zs\<0x[0-9a-z]\+\> /
    syntax match Conceal /No symbol table info available./
    syntax match Conceal /No locals./
    highlight GdbArgs guifg=#887ec8
  ]])
end

local function highlight_args()
  vim.cmd([[
    syntax clear
    syntax match Title /^Args$/
    syntax match GdbArgs /\<\zs\w\+\ze\> =/
    syntax match Conceal / = \zs\<0x[0-9a-z]\+\> /
    syntax match Conceal /No symbol table info available./
    syntax match Conceal /No arguments./
    highlight GdbArgs guifg=#887ec8
  ]])
end

local function render(self, data, console, frame, locals, args)
  if self.mode == "normal" then
    vim.api.nvim_buf_set_text(
      console.bufnr,
      -1,
      -1,
      -1,
      -1,
      vim.split(data, "\n")
    )
  elseif self.mode == "frame" then
    local filename, code_str = data:match("at (.*):%d*\n(.*)%(gdb%)")
    filename = filename and filename or data:match(" from (.*)\n+")
    local frame_str = (code_str and ("Frame\n▸ %s\n  %s"):format(
      filename,
      code_str
    ) or (filename and "Frame\n▸ " .. filename or "Frame")):gsub(
      "%(gdb%) ",
      ""
    )
    vim.api.nvim_buf_set_lines(
      frame.bufnr,
      0,
      -1,
      false,
      vim.split(frame_str, "\n")
    )
    coroutine.resume(self.co)
  elseif self.mode == "locals" then
    local locals_str = data:match("(.*)\n%(gdb%).*")
    locals_str = (locals_str and "Locals\n" .. locals_str or "Locals"):gsub(
      "%(gdb%) ",
      ""
    )
    vim.api.nvim_buf_set_lines(
      locals.bufnr,
      0,
      -1,
      false,
      vim.split(locals_str, "\n")
    )
    coroutine.resume(self.co)
  elseif self.mode == "args" then
    local args_str = data:match("(.*)\n%(gdb%).*")
    args_str = (args_str and "Args\n" .. args_str or "Args"):gsub(
      "%(gdb%) ",
      ""
    )
    vim.api.nvim_buf_set_lines(
      args.bufnr,
      0,
      -1,
      false,
      vim.split(args_str, "\n")
    )
    coroutine.resume(self.co)
  end
end

function M:layout()
  local source = {
    winid = vim.api.nvim_get_current_win(),
    bufnr = vim.api.nvim_get_current_buf(),
  }

  local win_options = {
    number = false,
    signcolumn = "no",
    winfixbuf = true,
    cursorline = false,
  }
  local locals = Split({ win_options = win_options })
  local args = Split({ win_options = win_options })
  local frame = Split({ win_options = win_options })
  local console = Split({ enter = false, win_options = win_options })

  local console_component = Layout(
    {
      relative = { type = "win", id = source.winid },
      position = "bottom",
      size = "50%",
    },

    Layout.Box({
      Layout.Box(console, { size = "100%" }),
    }, { dir = "row" })
  )

  local watch_component = Layout(
    {
      relative = "editor",
      position = "left",
      size = "30%",
    },
    Layout.Box({
      Layout.Box(locals, { size = "35%" }),
      Layout.Box(args, { size = "35%" }),
      Layout.Box(frame, { size = "30%" }),
    }, { dir = "col" })
  )
  console:map("n", "<cr>", function()
    local line = vim.api.nvim_get_current_line()
    local frame_num, filename, lnum =
      line:match("#(%d+) .* in .* at (.*):(%d+)")
    frame_num = frame_num and frame_num or line:match("#(%d+) .* from .*")

    -- Display source code
    if filename then
      local bufnr = vim.fn.bufnr(filename)
      if bufnr == -1 then
        bufnr = vim.fn.bufadd(filename)
      end

      vim.fn.bufload(bufnr)
      vim.api.nvim_win_set_buf(source.winid, bufnr)
      vim.api.nvim_win_set_cursor(source.winid, { tonumber(lnum), 0 })
      vim.wo[source.winid].cursorline = true
    else
      vim.api.nvim_win_set_buf(source.winid, source.bufnr)
    end

    coroutine.wrap(function()
      self.co = assert(coroutine.running())
      if self.job then
        self.mode = "frame"
        self.job:write(("frame %s\n"):format(frame_num))
        coroutine.yield()
        self.mode = "locals"
        self.job:write("info locals\n")
        coroutine.yield()
        self.mode = "args"
        self.job:write("info args\n")
        coroutine.yield()
      end
    end)()
  end, { noremap = true })

  vim.schedule(function()
    watch_component:mount()
    vim.api.nvim_set_current_win(source.winid)
    console_component:mount()
    vim.api.nvim_set_current_win(console.winid)

    pcall(vim.api.nvim_win_call, console.winid, highlight_console)
    pcall(vim.api.nvim_win_call, frame.winid, highlight_frame)
    pcall(vim.api.nvim_win_call, locals.winid, highlight_locals)
    pcall(vim.api.nvim_win_call, args.winid, highlight_args)
  end)
  return locals, args, frame, console, source
end

function M.setup(opts)
  M = vim.tbl_deep_extend("force", M, opts)
  vim.api.nvim_create_autocmd("BufReadCmd", {
    pattern = M.pattern,
    callback = function(args)
      local core = args.file
      M:gdb_start(core)
    end,
  })
end

function M:gdb_start(core)
  local env_file = vim.fs.joinpath(vim.uv.cwd(), self.config_name)

  local locals, args, frame, console, source = self:layout()

  return coroutine.wrap(function()
    local co = assert(coroutine.running())
    vim.uv.fs_open(env_file, "r", 438, function(err, fd)
      if err and vim.startswith(err, "ENOENT") then
        coroutine.resume(co, fd)
        return
      end
      assert(not err, err)
      coroutine.resume(co, fd)
    end)
    local fd = coroutine.yield()

    if fd == nil then
      return
    end

    vim.uv.fs_fstat(fd, function(err, stat)
      assert(not err)
      coroutine.resume(co, stat.size)
    end)
    local size = coroutine.yield()
    if size == 0 then
      return
    end

    vim.uv.fs_read(fd, size, 0, function(err, data)
      assert(not err)
      vim.uv.fs_close(fd)
      local lines = vim.split(data, "\n")
      for _, line in ipairs(lines) do
        if line:find("^ELF") then
          self.elf = line:sub(#"ELF" + 2, #line)
        end
      end
      coroutine.resume(co, true)
    end)
    coroutine.yield()

    self.job = vim.system(
      { "gdb", self.elf, core, "-ex", "set width unlimited", "-ex", "bt" },
      {
        stdin = true,
        stdout = vim.schedule_wrap(function(err, data)
          if err or not data then
            return
          end
          render(self, data, console, frame, locals, args)
        end),
        stderr = vim.schedule_wrap(function(err, data)
          if err or not data then
            return
          end
          render(self, data, console, frame, locals, args)
        end),
      }
    )
  end)()
end

return M
