local progress = { idx = -1 }

local M = {
  job = nil,
  mode = "console",
  co = nil,
  progress = progress,
}

local Split = require("nui.split")
local Layout = require("nui.layout")
local event = require("nui.utils.autocmd").event

function progress:start()
  if self.client_id and vim.lsp.get_client_by_id(self.client_id) then
    return
  end
  self.client_id = vim.lsp.start({
    name = "Corefile",
    cmd = { "tail", "-f", "/dev/null" },
    root_dir = vim.loop.cwd(),
  })
end

function progress:stop()
  local client = vim.lsp.get_client_by_id(self.client_id)
  if client then
    client:stop()
  end
  self.idx = -1
  self.client_id = nil
end

function progress:emit(ev)
  self.idx = self.idx + 1
  ev.percentage = ev.percentage or math.floor(100 * self.idx / (self.idx + 1))
  vim.api.nvim_exec_autocmds("LspProgress", {
    data = {
      client_id = self.client_id,
      params = {
        token = "load-corefile-progress",
        value = {
          kind = ev.kind,
          title = ev.title,
          message = ev.message,
          percentage = ev.percentage,
        },
      },
    },
  })
end

local function highlight_console()
  vim.cmd([[
    syntax clear
    syntax match GdbLink /<\zs[^>]\+\ze>/
    syntax match GdbMark /GNU gdb (GDB) .\+/
    syntax match GdbImportItem /Reading symbols from .\+/
    syntax match GdbImportItem /Core was generated by .\+/
    syntax match GdbAddress / \<0x[0-9a-z]\+\> /
    syntax match Conceal /=\zs\<0x[0-9a-z]\+\> /
    syntax match Conceal /\.\.\.\+/
    syntax match Conceal /<optimized out>/
    syntax match String /"[^"]\+"/
    syntax match String /'[^']\+'/
    syntax match Boolean /\<true\>/
    syntax match Boolean /\<false\>/
    syntax match GdbFunction /in \zs[^ ]\+/
    syntax match GdbArgs /\<\zs\w\+\ze\>=/
    syntax match GdbLink /) from \zs.*$/
    syntax match GdbLinkItalic /at \zs[^ ]\+:\d\+$/
    syntax match ErrorMsg /^❌️ .*/
  ]])
end

local function highlight_frame()
  vim.cmd([[
    syntax clear
    syntax match Title /^Frame$/
    syntax match CursorLineNr /  \zs\d\+\ze[\t\s]\+/
    syntax match String /▸ .*/
    syntax match Keyword /(.*)\ze\s*▸ .*/
    syntax match ErrorMsg /:\s*\zsNo such file or directory./
  ]])
end

local function highlight_locals()
  vim.cmd([[
    syntax clear
    syntax match Title /^Locals$/
    syntax match GdbArgs /\<\zs\w\+\ze\> =/
    syntax match Conceal / = \zs\<0x[0-9a-z]\+\> /
    syntax match Conceal /No symbol table info available./
    syntax match Conceal /No locals./
    syntax match Conceal /<optimized out>/
    syntax match Boolean /\<true\>/
    syntax match Boolean /\<false\>/
    syntax match Number /\<\d\+\>/
    syntax match String /"[^"]\+"/
    syntax match String /'[^']\+'/
  ]])
end

local function highlight_args()
  vim.cmd([[
    syntax clear
    syntax match Title /^Args$/
    syntax match GdbArgs /\<\zs\w\+\ze\> =/
    syntax match Conceal / = \zs\<0x[0-9a-z]\+\> /
    syntax match Conceal /No symbol table info available./
    syntax match Conceal /No arguments./
    syntax match Conceal /<optimized out>/
    syntax match Boolean /\<true\>/
    syntax match Boolean /\<false\>/
    syntax match Number /\<\d\+\>/
    syntax match String /"[^"]\+"/
    syntax match String /'[^']\+'/
  ]])
end

local function render(self, data, console, frame, locals, args, buffers)
  if data:find("__args__ start") then
    data = data:gsub("__args__ start", "")
    self.mode = "args"
  end
  if self.mode == "args" then
    buffers.args = buffers.args .. data
    if data:find("__args__ end") then
      buffers.args = buffers.args:gsub("__args__ end", "")
      local args_str = buffers.args
      args_str = args_str:gsub("%(gdb%)%s*", "")
      vim.api.nvim_buf_set_text(
        args.bufnr,
        -1,
        -1,
        -1,
        -1,
        vim.split(args_str, "\n")
      )
      buffers.args = ""
      coroutine.resume(self.co)
    end
  end

  if data:find("__locals__ start") then
    data = data:gsub("__locals__ start", "")
    self.mode = "locals"
  end
  if self.mode == "locals" then
    buffers.locals = buffers.locals .. data
    if data:find("__locals__ end") then
      buffers.locals = buffers.locals:gsub("__locals__ end", "")
      local locals_str = buffers.locals or ""
      locals_str = locals_str:gsub("%(gdb%)%s*", "")
      vim.api.nvim_buf_set_text(
        locals.bufnr,
        -1,
        -1,
        -1,
        -1,
        vim.split(locals_str, "\n")
      )
      buffers.locals = ""
      coroutine.resume(self.co)
    end
  end

  if data:find("__frame__ start") then
    data = data:gsub("__frame__ start", "")
    self.mode = "frame"
  end
  if self.mode == "frame" then
    buffers.frame = buffers.frame .. data
    if data:find("__frame__ end") then
      buffers.frame = buffers.frame:gsub("__frame__ end", "")
      local function_name, filename, code_str =
        buffers.frame:match("#%d+ .* in (.*) %(.*at (.*):%d*\n(.*)%(gdb%)")
      filename = filename and filename or buffers.frame:match(" from (.*)\n+")
      if filename == nil then
        function_name, filename, code_str =
          buffers.frame:match("#%d+%s*(.*) %(.*at (.*):%d*\n(.*)%(gdb%)")
      end

      local frame_str = (code_str and ("(%s) ▸ %s\n  %s"):format(
        function_name,
        filename,
        code_str
      ) or (filename and "▸ " .. filename or "")):gsub("%(gdb%) ", "")

      vim.api.nvim_buf_set_text(
        frame.bufnr,
        -1,
        -1,
        -1,
        -1,
        vim.split(frame_str, "\n")
      )
      buffers.frame = ""
      coroutine.resume(self.co)
    end
  end

  if self.mode:find("console") then
    local lines_list = vim.split(data, "\n")
    vim.api.nvim_buf_set_text(console.bufnr, -1, -1, -1, -1, lines_list)
    if self.mode == "console-cmd" then
      vim.api.nvim_win_set_cursor(console.winid, {
        vim.api.nvim_buf_line_count(console.bufnr),
        #vim.api.nvim_get_current_line(),
      })
    else
      if lines_list[#lines_list] == "(gdb) " then
        self.progress:emit({
          kind = "end",
          percentage = 100,
          message = "",
          title = "Done",
        })
      else
        self.progress:emit({
          kind = "report",
          message = "",
          title = "Loading",
        })
      end
    end
  end
end

function M:layout()
  local source = {
    winid = vim.api.nvim_get_current_win(),
    bufnr = vim.api.nvim_get_current_buf(),
  }

  local win_options = {
    number = false,
    signcolumn = "no",
    winfixbuf = true,
    cursorline = false,
  }
  local locals = Split({ win_options = win_options })
  local args = Split({ win_options = win_options })
  local frame = Split({ win_options = win_options })
  local console = Split({
    enter = false,
    win_options = vim.tbl_deep_extend(
      "force",
      win_options,
      { cursorline = true }
    ),
  })

  local console_component = Layout(
    {
      relative = { type = "win", id = source.winid },
      position = "bottom",
      size = "50%",
    },

    Layout.Box({
      Layout.Box(console, { size = "100%" }),
    }, { dir = "row" })
  )

  local watch_component = Layout(
    {
      relative = "editor",
      position = "left",
      size = "30%",
    },
    Layout.Box({
      Layout.Box(locals, { size = "35%" }),
      Layout.Box(args, { size = "35%" }),
      Layout.Box(frame, { size = "30%" }),
    }, { dir = "col" })
  )

  for _, comp in pairs({ console, locals, args, frame }) do
    comp:on(event.WinClosed, function()
      self.progress:stop()
      vim.uv.kill(-self.job.pid, "sigterm")
      console_component:unmount()
      watch_component:unmount()
    end)
  end

  console:map("i", "<cr>", function()
    self.mode = "console-cmd"
    vim.api.nvim_buf_set_lines(console.bufnr, -1, -1, false, { "" })
    local cmd = vim.api.nvim_get_current_line():gsub("%(gdb%)", "") .. "\n"
    self.job:write(cmd)
  end)

  console:map("n", "<cr>", function()
    self.mode = "console"
    vim.api.nvim_buf_set_lines(frame.bufnr, 0, -1, false, { "Frame", "" })
    vim.api.nvim_buf_set_lines(locals.bufnr, 0, -1, false, { "Locals", "" })
    vim.api.nvim_buf_set_lines(args.bufnr, 0, -1, false, { "Args", "" })
    local line = vim.api.nvim_get_current_line()
    local frame_num, filename, lnum =
      line:match("#(%d+) .* in .* at (.*):(%d+)")
    frame_num = frame_num and frame_num or line:match("#(%d+) .* from .*")
    if frame_num == nil then
      frame_num, filename, lnum = line:match("#(%d+) .* at (.*):(%d+)")
    end

    filename = (
      filename
      and (not vim.startswith(filename, "/"))
      and self.src_dir
    )
        and vim.fs.joinpath(self.src_dir, filename)
      or filename

    -- Display source code
    if filename and vim.fn.filereadable(filename) == 1 then
      local bufnr = vim.fn.bufnr(filename)
      if bufnr == -1 then
        bufnr = vim.fn.bufadd(filename)
      end

      vim.fn.bufload(bufnr)
      vim.api.nvim_win_set_buf(source.winid, bufnr)
      vim.api.nvim_win_set_cursor(source.winid, { tonumber(lnum), 0 })
      vim.wo[source.winid].cursorline = true
    else
      vim.api.nvim_win_set_buf(source.winid, source.bufnr)
    end

    coroutine.wrap(function()
      self.co = assert(coroutine.running())
      if self.job then
        self.job:write("echo __frame__ start\n")
        self.job:write(("frame %s\n"):format(frame_num))
        self.job:write("echo __frame__ end\n")
        coroutine.yield()

        self.job:write("echo __locals__ start\n")
        self.job:write("info locals\n")
        self.job:write("echo __locals__ end\n")
        coroutine.yield()

        self.job:write("echo __args__ start\n")
        self.job:write("info args\n")
        self.job:write("echo __args__ end\n")
        coroutine.yield()
      end
    end)()
  end, { noremap = true })

  vim.schedule(function()
    watch_component:mount()
    vim.api.nvim_set_current_win(source.winid)
    console_component:mount()
    local ns = vim.api.nvim_create_namespace("console_ns")
    vim.api.nvim_set_hl(ns, "CursorLine", { bold = true })
    vim.api.nvim_win_set_hl_ns(console.winid, ns)
    vim.api.nvim_set_current_win(console.winid)

    pcall(vim.api.nvim_win_call, console.winid, highlight_console)
    pcall(vim.api.nvim_win_call, frame.winid, highlight_frame)
    pcall(vim.api.nvim_win_call, locals.winid, highlight_locals)
    pcall(vim.api.nvim_win_call, args.winid, highlight_args)
  end)
  return locals, args, frame, console, source
end

function M.setup(opts)
  M = vim.tbl_deep_extend("force", M, opts)
  vim.api.nvim_create_autocmd("BufReadCmd", {
    pattern = M.pattern,
    callback = function(args)
      local core = args.file
      M:gdb_start(core)
    end,
  })
end

function M:gdb_start(core)
  self.progress:start()
  local env_file = vim.fs.joinpath(vim.uv.cwd(), self.config_name)
  local locals, args, frame, console, source = self:layout()

  return coroutine.wrap(function()
    local co = assert(coroutine.running())
    vim.uv.fs_open(env_file, "r", 438, function(err, fd)
      if err and vim.startswith(err, "ENOENT") then
        coroutine.resume(co, fd)
        return
      end
      assert(not err, err)
      coroutine.resume(co, fd)
    end)
    local fd = coroutine.yield()

    if fd == nil then
      return
    end

    vim.uv.fs_fstat(fd, function(err, stat)
      assert(not err)
      coroutine.resume(co, stat.size)
    end)
    local size = coroutine.yield()
    if size == 0 then
      return
    end

    vim.uv.fs_read(fd, size, 0, function(err, data)
      assert(not err)
      vim.uv.fs_close(fd)
      local lines = vim.split(data, "\n")
      for _, line in ipairs(lines) do
        if line:find("^ELF") then
          self.elf = line:sub(#"ELF" + 2, #line)
        end
        if line:find("^SRC_DIR") then
          self.src_dir = line:sub(#"SRC_DIR" + 2, #line)
        end
      end
      coroutine.resume(co, true)
    end)
    coroutine.yield()

    local buffers = {
      locals = "",
      args = "",
      frame = "",
      console = "",
    }

    self.job = vim.system({
      "gdb",
      self.elf,
      core,
      "-ex",
      "set width unlimited",
      "-ex",
      "bt",
    }, {
      stdin = true,
      stdout = vim.schedule_wrap(function(err, data)
        if err or not data then
          return
        end
        render(self, data, console, frame, locals, args, buffers)
      end),
      stderr = vim.schedule_wrap(function(err, data)
        if err or not data then
          return
        end
        render(self, data, console, frame, locals, args, buffers)
      end),
    })
  end)()
end

return M
